### PR TITLE
fixing github actions

### PR DESCRIPTION
**Pull request by bmlui**
merged from https://github.com/CS3733-SA23/starter-code/pull/42

### CODE REVIEW

**Review by bmlui — COMMENTED** [review]
auto gradle checks now working.

**Review by C-beaus — COMMENTED** [review]
Need to ensure we all have our local repos set to a project structure of java 17

**Review by C-beaus — COMMENTED** [review]
Is this a file we are meant to touch though? Or is this fixing a mistake made by the SAs

**Comment by bmlui** [comment]
@C-beaus not sure. It’s a PR of a commit from the SA branch fixing GitHub actions.

**Review by C-beaus — APPROVED** [review]
changing java version

**Pull request merged**
